//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enlighten.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Company()
        {
            this.TB_Godown = new HashSet<TB_Godown>();
            this.TB_Inventory = new HashSet<TB_Inventory>();
            this.TB_Product = new HashSet<TB_Product>();
            this.TB_ProductCategory = new HashSet<TB_ProductCategory>();
            this.TB_User = new HashSet<TB_User>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string HeaderInfoFirst { get; set; }
        public string HeaderInforSecond { get; set; }
        public string HeaderInforThird { get; set; }
        public string FooterInfoFirst { get; set; }
        public string FooterInfoSecond { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Godown> TB_Godown { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Inventory> TB_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Product> TB_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ProductCategory> TB_ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_User> TB_User { get; set; }
    }
}
