//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enlighten.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Inventory
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<System.DateTime> DateInward { get; set; }
        public Nullable<System.DateTime> DateOutward { get; set; }
        public Nullable<int> GodownID { get; set; }
        public int CompanyID { get; set; }
    
        public virtual TB_Company TB_Company { get; set; }
        public virtual TB_Godown TB_Godown { get; set; }
        public virtual TB_Product TB_Product { get; set; }
    }
}
