//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enlighten.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Product()
        {
            this.TB_Inventory = new HashSet<TB_Inventory>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> UnitSize { get; set; }
        public string Barcode { get; set; }
        public string Brand { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CompanyID { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string ModelName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Inventory> TB_Inventory { get; set; }
        public virtual TB_ProductCategory TB_ProductCategory { get; set; }
        public virtual TB_Company TB_Company { get; set; }
    }
}
